// Code generated by go-swagger; DO NOT EDIT.

// Package restapi User API
//
//	API for managing users
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /v1
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
